package com.nyasa.notifybridge.localization

/**
 * Typed scope for localized strings.
 *
 * Each `data object` here corresponds to a top-level group in the JSON source
 * (`app/src/main/assets/localization/<locale>/strings.json`). Per-scope `val`s and
 * `fun`s are generated by `build-logic`'s `LocalizationJsonToKotlinTask` into
 * `<Scope>StringExtensions.kt` and live in `build/generated/source/localization/`.
 */
sealed class Dictionary protected constructor(
    internal val dictionaryKey: String,
) {
    data object Onboarding : Dictionary("onboarding")
    data object Broker : Dictionary("broker")
    data object Status : Dictionary("status")
    data object Apps : Dictionary("apps")
    data object Permissions : Dictionary("permissions")
    data object Locked : Dictionary("locked")
    data object Services : Dictionary("services")
    data object Common : Dictionary("common")
    data object Language : Dictionary("language")
}

/**
 * Internal factory used by generated extensions. Splits `params` into plain args
 * and nested [StringContent] args so the resolver can run them through the same
 * language pass.
 */
internal fun Dictionary.localizedString(
    key: String,
    vararg params: Pair<String, Any>,
): LocalizedString {
    val localizableArgs = params
        .filter { it.second is StringContent }
        .associate { (k, v) -> k to (v as StringContent) }
    val args = params
        .filterNot { it.second is StringContent }
        .associate { (k, v) -> k to v }
    return LocalizedString(
        key = key,
        dictionary = dictionaryKey,
        args = args,
        localizableArgs = localizableArgs,
    )
}
